Create `Constants` file
NordicPlayground/robot-war-app pull request #17
Opened 2022-07-05 08:18 UTC by MLopezJ

New file with the main propose of have constants variables of the application.

2022-07-05 13:57 UTC, Semikaja approved these changes

2022-07-05 14:29 UTC, Lenakh97 approved these changes

2022-07-06 07:31 UTC, coderbyheart requested changes

2022-07-06 07:31 UTC, coderbyheart commented on src/utils/constants.ts
> +export const randomColor = (): string =>
**nitpick**: I prefer functions to be in their own files.

2022-07-06 07:31 UTC, coderbyheart commented on src/utils/constants.ts
> +export const defaultOponentTeamColor = '#000000'
This should go in the [appConfig](https://github.com/NordicPlayground/robot-war-app/blob/4386aa4c837775d8d839dee203e3f76660122cde/src/hooks/useAppConfig.tsx) hook, so we have one place for application configuration.

2022-07-06 09:47 UTC, merged